#pragma once

namespace test
{
    #define DECLARE_TEST_TYPE(TYPE_NAME) struct TYPE_NAME {};

    DECLARE_TEST_TYPE(T0)
    DECLARE_TEST_TYPE(T1)
    DECLARE_TEST_TYPE(T2)
    DECLARE_TEST_TYPE(T3)
    DECLARE_TEST_TYPE(T4)
    DECLARE_TEST_TYPE(T5)
    DECLARE_TEST_TYPE(T6)
    DECLARE_TEST_TYPE(T7)
}