language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8

before_install:
  - eval "CC=gcc-8 && CXX=g++-8"

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make && make test