#pragma once

#include "cpputil\reference_wrapper.h"
#include "cpputil\operator_functors.h"
#include "cpputil\foreach_argument.h"
#include "cpputil\transform_type.h"
#include "cpputil\rename_type.h"
#include "cpputil\packer.h"
#include "cpputil\not_fn.h"
#include "cpputil\apply.h"
#include "cpputil\as_const.h"
#include "cpputil\exchange.h"
#include "cpputil\declval.h"
#include "cpputil\forward.h"
#include "cpputil\move.h"
